name: Build and Deploy to Cloud Run For Dev

on:
  push:
    branches:
      - ms-payment/dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.3.0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Configure Docker
      run: |
        gcloud auth configure-docker

    - name: create-cred-firebase-json
      id: create-cred-firebase-json
      uses: jsdaniell/create-json@v1.2.2
      with:
        name: "firebase_credential.json"
        json: ${{secrets.FIREBASE_CREDENTIAL}}
    
    - name: Build and push Docker image
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/ms-payment-test:${{ github.sha }} .
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/ms-payment-test:${{ github.sha }}

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy ms-payment-test \
        --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/ms-payment-test:${{ github.sha }} \
        --region asia-southeast1 \
        --platform managed \
        --allow-unauthenticated \
        --set-env-vars DB_USER=${{ secrets.DB_USER }},DB_PASSWORD=${{ secrets.DB_PASSWORD }},DB_HOST=${{ secrets.DB_HOST }},DB_PORT=${{ secrets.DB_PORT }},DB_NAME=${{ secrets.DB_NAME_DEV }},DEPLOY=PROD,GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }},STRIPE_KEY=${{ secrets.STRIPE_KEY_TEST }},GIN_MODE=release,ENV=Production,FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }},AES_KEY=${{ secrets.AES_KEY }},AES_VI=${{ secrets.AES_VI }} \
        --max-instances=10 \
        --memory 1Gi \
        --timeout=1m